accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('follow/<int:movie_id>/', views.follow, name="follow"),
]

movie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('watch.urls')),
    path('accounts/', include('accounts.urls')),
]

watch/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'watch'

urlpatterns = [
    path('', views.index, name='index'),
    path('schedule/', views.schedule, name='schedule'),
    path('zzims/', views.zzim_list, name='zzim_list'),
    path('mypage/', views.mypage, name='mypage'),
    path('movies/<int:movie_id>/', views.movie_detail, name="movie_detail"),
    path('search_movie/', views.search_movie, name="search_movie"),
    # path('make_schedule/', views.make_schedule, name='make_schedule'),
    path('make_movie/', views.make_movie, name='make_movie'),
    path('go_to/<str:movie_name>/', views.go_to, name="go_to"),
    path('movies/<int:movie_id>/create_comment/', views.create_comment, name="create_comment"),
    url(r'^movie-autocomplete/', views.MovieAutocomplete.as_view(), name='movie-autocomplete'),
    path('schedule/search/', views.search_schedule, name='search_schedule'),
]

schedule/models.py
from django.db import models

# Create your models here.

watch/models.py
from django.db import models
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django_extensions.db.models import TimeStampedModel


# Create your models here.
class Schedule(models.Model):
    title = models.CharField(max_length=50)
    datetime = models.DateTimeField()
    channel = models.CharField(max_length=20)
    
    def __str__(self):
        return f"{self.id} / {self.title} / {self.channel} / {self.datetime}"
        
class Movie(models.Model):
    title = models.CharField(max_length=50)
    posterUrl = models.TextField(blank=True)
    productionYear = models.IntegerField(default=0, null=True)
    genre = models.CharField(max_length=50, blank=True)
    country = models.CharField(max_length=50, blank=True)
    runningTime = models.IntegerField(default=0, null=True)
    # 10점만점
    score = models.DecimalField(decimal_places=2, max_digits=10, default=0, null=True)
    # 1.6만명, 단위가 만 명이라능
    audience = models.CharField(max_length=20, blank=True)
    content = models.TextField(blank=True)
    director = models.CharField(max_length=50, blank=True)
    follows = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='followers', blank=True)

    def __str__(self):
        # return f"{self.id} / {self.title}"
        return f"{self.title}"

class Comment(models.Model):
    content = models.CharField(max_length=140, blank=True)
    score = models.IntegerField(validators=[
            MaxValueValidator(10),
            MinValueValidator(1)
        ])
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='user_comments', on_delete=models.CASCADE)
    movie = models.ForeignKey(Movie, related_name="movie_comments", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def _str__(self):
        return self.content

    
class QueryModel(models.Model):
    content = models.ForeignKey(Movie, on_delete=models.CASCADE)

watch/forms.py
from dal import autocomplete
from django import forms
from .models import QueryModel, Comment, Movie


class SearchForm(forms.ModelForm):
    content = forms.ModelChoiceField(
        Movie.objects.all(),
        widget=autocomplete.ModelSelect2(url='watch:movie-autocomplete')
        )
        
    class Meta:
        model = QueryModel
        fields = ('__all__')
    # 이전 버전
    # class Meta:
    #     model = QueryModel
    #     fields = ('__all__')
    #     widgets = {
    #         'content': autocomplete.ModelSelect2(url='watch:movie-autocomplete'),
    #     }
        
    #     birth_country = forms.ModelChoiceField(
    #     queryset=Country.objects.all(),
    #     widget=autocomplete.ModelSelect2(url='country-autocomplete')
    # )

    # class Meta:
    #     model = Person
    #     fields = ('__all__')
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content', 'score')

schedule/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
# Create your views here.
import requests
import time
import json
import urllib.request
from datetime import datetime
# 무조건 7개 날짜씩
# 날짜별로 matrix 만들기, 행은 채널, 칼럼은 시간
month = datetime.today().month
day = datetime.today().day
url = 'https://search.daum.net/search?nil_suggest=btn&w=tot&DA=SBC&q='+str(month)+'월+'+str(day)+'일+케이블+영화_편성표'

watch/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
import os, requests, json, random
from bs4 import BeautifulSoup
from datetime import datetime, date
from .models import Schedule, Movie, Comment
from .forms import SearchForm, CommentForm
from dal import autocomplete
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.core import serializers


# Create your views here.
@login_required
def index(request):
    # index 배경 이미지 랜덤 선택
    background_image_cnt = 8
    background_num = random.randint(1, background_image_cnt)
    
    # 검색어 자동완성 Form
    form = SearchForm()
    
    # 찜한 영화가 스케쥴에 있는지
    zzim_ready = []
    if request.user.is_authenticated:
        zzimList = request.user.followers.all()
        today = datetime.now()
        print(today)
        max_date = Schedule.objects.all().order_by('-datetime')[0].datetime
        print("max date: ", max_date)
        #schedules = Schedule.objects.filter(datetime__range=(today, max_date))
        schedules = Schedule.objects.filter(datetime__date__gte=today)
        
        for schedule in schedules:
            # 네이버 제목으로 바꿔
            for zzim in zzimList:
                if zzim.title == schedule.title:
                    zzim_ready.append([zzim, schedule.datetime.strftime("%m/%d %a %H:%M"), schedule.channel])
    
    # 편성표 중 추천 영화 랜덤 선택
    schedules = Schedule.objects.all()
    recommend_schedule = 0
    recommend_movie = 0
    while not (recommend_schedule and recommend_movie):
        recommend_num = random.randint(schedules[0].id, schedules.order_by('-id')[0].id)
        recommend_schedule = Schedule.objects.get(pk=recommend_num)
        print(recommend_schedule)
        filter_list = Movie.objects.filter(title=recommend_schedule.title)
        if filter_list:
            recommend_movie = filter_list[0]
    context = {
        'zzim_ready' : zzim_ready,
        'background_url': f'image/index/{background_num}.jpg' if background_num == 2 or background_num == 3 else f'image/index/{background_num}.png',
        'recommend_schedule': recommend_schedule,
        'recommend_movie': recommend_movie,
        'recommend_datetime': recommend_schedule.datetime.strftime("%m/%d %a %H:%M"),
        'form': form,
    }
    return render(request, 'watch/index.html', context)
    


def schedule(request):
    # 검색어 자동완성 Form
    form = SearchForm()
    
    schedules = Schedule.objects.all().order_by('channel', 'datetime')
    print(schedules)
    data = {}
    for schedule in schedules:
        this_date = schedule.datetime.strftime("%m/%d %a")
        data[this_date] = {'ocn':{}, 'cgv': {}, 'super_action': {}, '스크린': {}}
    for schedule in schedules:
        this_date = schedule.datetime.strftime("%m/%d %a")
        this_time = schedule.datetime.strftime("%H:%M")
        data[this_date][schedule.channel][this_time] = schedule.title
    # print(data)
    context = {
        'schedules': schedules,
        'data': data,
        'json_data' : json.dumps(data),
        'form' : form,
    }
    return render(request, 'watch/schedule.html', context)


def search_schedule(request):
    form = SearchForm()
    print(request.POST)
    channel_name = request.POST.get('channel_name')
    print("채널", channel_name)
    schedules = Schedule.objects.filter(channel=channel_name).order_by('channel', 'datetime')
    data = {}
    for schedule in schedules:
        this_date = schedule.datetime.strftime("%m/%d %a")
        data[this_date] = {'ocn':{}, 'cgv': {}, 'super_action': {}, '스크린': {}}
    for schedule in schedules:
        this_date = schedule.datetime.strftime("%m/%d %a")
        this_time = schedule.datetime.strftime("%H:%M")
        data[this_date][schedule.channel][this_time] = schedule.title
    context = {
        'search_schedules': data,
        'channel_name': channel_name,
        'form': form,
    }
    return render(request, 'watch/schedule_channel.html', context)

# 'zzims/<str:user_name>/', views.zzim_list, name='zzim_list'
# 문제점 : 찜하기 이후 페이지가 다시 rendering되면서 처음부터 스크롤을 다시 내려서 봐야 한다.
@login_required
def zzim_list(request):
    # 검색어 자동완성 Form
    form = SearchForm()
    
    like_movies = request.user.followers.all()
    movies = Movie.objects.all()
    
    context = {
        'like_movies' :like_movies,
        'movies' : movies,
        'form' : form,
    }
    return render(request, 'watch/zzim_list.html', context)


@login_required
def mypage(request):
    # 검색어 자동완성 Form
    form = SearchForm()
    
    like_movies = request.user.followers.all()
    context = {
        'like_movies' :like_movies,
        'form': form,
    }
    return render(request, 'watch/mypage.html', context)

@login_required
def movie_detail(request, movie_id):
    # 검색어 자동완성 Form
    form = SearchForm()
    
    movie = Movie.objects.get(pk=movie_id)
    comments = movie.movie_comments.all()
    comment_form = CommentForm()
    context = {
        'comment_form' : comment_form,
        'movie': movie,
        'comments' : comments,
        'form' : form,
    }
    return render(request, 'watch/movie_detail.html', context)

@login_required
def create_comment(request, movie_id):
    comment_form = CommentForm(request.POST)
    movie=Movie.objects.get(pk=movie_id)
    if request.method == 'POST':
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.created_by = request.user
            comment.movie_id = movie.id
            comment.save()
    return redirect('watch:movie_detail', movie.id)

@login_required
def go_to(request, movie_name):
    movie = get_object_or_404(Movie, title=movie_name)
    return redirect('watch:movie_detail', movie.id)


class MovieAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        # if not self.request.user.is_authenticated():
        #     return Movie.objects.none()
        qs = Movie.objects.all()
        if self.q:
            qs = qs.filter(title__istartswith=self.q)
        return qs


def search_movie(request):
    # query = request.POST.form_search
    # query = request.
    movie = get_object_or_404(Movie, pk=request.POST.get('content'))
    
    return redirect('watch:movie_detail', movie.id)
    


# Search FormVIew
# class SearchView(FormView):
#     template_name = 'base.html'
#     form_class = UserCreationForm
#     success_url = ''
    
#     def form_valid(self, form):
#         print(form.data['content'])
#         return super().form_valid(form)


def make_movie(request):
    failed_list = []
    # python file의 위치
    # BASE_DIR = os.path.dirname(os.path.abspath(__file__))
    # print(table.prettify())
    
    # 목표 : 한 방송사가 한 행, 시간이 칼럼
    # date도 넣어주어야
    # db에 넣을 때 date, 방송사, 시간 - 영화 pair
    # '선샤인<1부>'같은건 링크 없으면 못 찾을 듯
    
    # 일주일치
    
    #### 채널 원래대로 다 넣어놓고, movie_title 구한 후 해당 movie_title이 없을 때 movie info 검색
    #### 영어 + 한글에서 한글 남겨둬야 할 수도...? 뭘 버려야 
    #### 유명한 시리즈물은 미리 DB에 넣어두어도 될 것 같다 -> 분노의 질주
    def make_schedule_for_seven_days():
        source = requests.get('https://search.daum.net/search?nil_suggest=btn&w=tot&DA=SBC&q=cgv+편성표').text
        soup = BeautifulSoup(source, "html.parser")
    
        data = {}
    
        Days = soup.find('div', class_="tbl_head head_type2")
        dayList = []
        for day in Days.find_all('span'):
            # day.span.text하니까 여러 개가 뽑혀서 이렇게
            if len(day.text) == 5:
                # print(day, day.text)
                data[day.text] = {'cgv':{}, 'ocn' : {}, 'super_action' : {}, '스크린': {}}
                dayList.append(day.text)
        
        def cleanedTitle(Title):
            Title = Title.strip()
            flag = False
            for j in range(len(Title)):
                #[오스카4관왕]버드맨
                if Title[3] == '[':
                    # 뒤에 진짜 제목이 있어야 해
                    for jj in range(4, len(Title)-1):
                        if Title[jj] == ']':
                            flag = True
                            # [007시리즈]007카지노로얄 <3부>, 십의 자리까지 있는 부는 없겠지
                            # [영상미폭발] 알로하 <1부>
                            if Title[len(Title)-2:len(Title)]=='부>' and 49 <= ord(str(Title[len(Title)-3])) <= 57:
                                Title = '영화' + Title[jj+1:len(Title)-4]
                                break
                            else:
                                Title = '영화' + Title[jj+1:len(Title)]
                                break
                    # 바깥쪽 for문 깨기
                    if flag:
                        break
                # R.I.P.D.유령퇴치전담반 : 영어만 쓴다
                if 97 <= ord(Title[3]) <= 122 or 65 <= ord(Title[3]) <= 90:
                    end_point = 3
                    for jj in range(3, len(Title)):
                        # 숫자인 것도 넣어야, GP506
                        if 97 <= ord(Title[jj]) <= 122 or 65 <= ord(Title[jj]) <= 90 or  48 <= ord(Title[jj]) <= 56:
                            end_point = jj
                    Title = Title[:end_point+1]
                    break
                
                # 브이아이피(V.I.P)라고 치면 검색이 제대로 이루어지지 않아서 추가, 등등 괄호 빼버리기
                if Title[j] == '(':
                    Title = Title[:j]
                    break
                # '잭 리처2:네버 고 백'인데 이렇게 검색하면 잘 안 나와, 잭 리처:네버 고 백 이어야
                # 이렇게 하면 쥬라기 공원2가 망해 -> 그냥 잭 리처2, 쥬라기 공원2로만 검색한다
                # 시리즈물일 때, :이나 - 다음 부제 나올 때 부제 빼버려
                #  or Title[j+1] == '-' : 이거 조건에서 지워야지
                if 48 <= ord(str(Title[j])) <= 57 and j>0:
                    if j+1<len(Title)-1 and (Title[j+1] == ':'):
                        Title = Title[:j]
                        break
                    elif j+2 < len(Title)-1 and (Title[j+2] == ':'):
                        Title = Title[:j+1]            

watch/templates/watch/mypage.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% load bootstrap4%}

<!--참고 : https://bootsnipp.com/snippets/KB2bD -->
{% block head %}
<!--<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">-->
<!--<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>-->
<!--<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>-->
<!------ Include the above in your HEAD tag ---------->
<link href="{% static 'css/my_page.css'%}" rel='stylesheet'>
<link href="{% static 'css/index_schedule.css' %}" type="text/css" rel="stylesheet">
<link href="{% static 'css/zzim_list.css'%}" rel='stylesheet'>
<style>
  .resize {
    width:10px;
  }
  .margin-bot {
    margin-bottom: 56px !important;
  }
</style>
<link href="{% static 'css/search_bar.css'%}" rel='stylesheet'>
{% endblock %}

{% block body %}
<nav class="">
  <div class="nav-wrapper row center">
      <div class="row center">
        <form class="form-inline" action="{% url 'watch:search_movie' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
              <button class="btn btn-color btn-xs ml-1" type="submit">검색</button>
            {% endbuttons %}
        </form>
      </div>
  </div>
</nav>
<!-- Jumbotron -->
<!--<div class="container">-->
<div class="jumbotron margin-bot">
 
  <!-- Title -->
  <div class="text-center">
  <!--<h3 class="display-4">{{movie.title}}</h3>-->
  <h4 class="card-title h2 pb-2 mb-3"><strong>{{request.user.username}}</strong></h4>

  <!-- Card image -->
  <div class="view overlay my-4">
    <img src="{% static 'image/동물들01.jpg' %}" class="img-fluid" alt="{{movie.title}}">
  </div>
		<!--<div class="d-flex justify-content-center h-100">-->
			
  
  
  <div class="container center">
  <div class="row text-center center">
		 <h4 class="text-center mx-auto">{{request.user}}님의 찜 리스트</h4>
<div style="width:100%">
  <div class="row justify-content-center">
    <section class="content">
    <!--<div class="col-md-8 col-md-offset-2">-->
    <div>
      <!--<div class="panel panel-default">-->
        <div class="pannel-body">
          <div class="table-container">
          <table class="table table-filter">
          <!--<table>-->
            <tbody>
              {% for movie in like_movies %}
              
              <tr data-status="pagado">
                <td>
                    <a href="{% url 'accounts:follow' movie.id %}"><i class="fas fa-heart"></i></a>
                </td>
                <td>
                  <img src="{{ movie.posterUrl }}" class="resize media-photo pull-left">
                </td>
                <td>
                  <div class="media">
                    <!--<div>-->
                    <a href="{% url 'watch:movie_detail' movie.id %}">
                      <!--media body때문에 오류났었음-->
                    <!--<div class="media-body">-->
                    <div>
                      <span class="media-meta pull-right">
                      <!--<span class="pull-right">-->
                        제작년도:{{movie.productionYear}}</span>
                      <h5 class="title">{{movie.title}}</h5>
                      <p class="summary">genre : {{movie.genre}} country : {{movie.country}} director : {{movie.director}}</p>
                    </div>
                    </a>
                  </div>
                </td>
              </tr>
              {% endfor %}
              </tbody>
          </table>
          </div>
        </div>
      <!--</div>-->
    </div>
    </section>
  </div>
  </div>
  </div>
  </div>
<a href="{% url 'accounts:logout' %}">로그아웃</a>
</div>
</div>
{% endblock %}

watch/templates/watch/schedule.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% load bootstrap4 %}

{% block head %}
<link href="{% static 'css/search_bar.css'%}" rel='stylesheet'>
<!-- Vue -->
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<style>
  .margin-bot {
    margin-bottom: 100px !important;
  }
</style>
{% endblock %}

{% block body %}
 <nav class="">
  <div class="nav-wrapper row center">
      <div class="row center">
        <form class="form-inline" action="{% url 'watch:search_movie' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
              <button class="btn btn-color btn-xs ml-1" type="submit">검색</button>
            {% endbuttons %}
        </form>
      </div>
  </div>
</nav>
<div id="app" data="{{ json_data }}">
  <div class="container">
    <!-- select option 채널 -->
      
    <form class="form-inline" action="{% url 'watch:search_schedule' %}" method="POST">
      {% csrf_token %}
      <label class="my-1 mr-2" for="inlineFormCustomSelectPref">편성표 보기</label>
      <select v-model="selected" class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref" name="channel_name">
        <option selected>채널선택</option>
        <option value="ocn">OCN</option>
        <option value="cgv">Channel CGV</option>
        <option value="super_action">Super Action</option>
        <option value="스크린">Screen</option>
      </select>
        <button type="submit" class="btn btn-primary my-1">검색</button>
    </form>
    <!-- 편성표 -->
    
  <!--  <table v-show="true" class="table table-bordered table-hover">-->
  <!--  <thead>-->
  <!--    <tr>-->
  <!--      <th scope="col">시간</th>-->
  <!--      <th scope="col">[[ selected ]]</th>-->
  <!--    </tr>-->
  <!--  </thead>-->
  <!--  <tbody>-->
        <!--<tr v-for="date in search_schedules">-->
        <!--  <th scope="row">[[ date ]]</th>-->
            <!--<td v-for="channel in search_schedules.date">-->
              <!--<a v-for="hour in search_schedules.date.channel" :href="" class="list-group list-group-flush list-group-item-action active">-->
            <!--    <div>[[ hour ]] [[ search_schedules.date.channel.hour ]]</div>-->
              <!--</a>-->
  <!--          </td>-->
  <!--      </tr>-->
  <!--  </tbody>-->
  <!--</table>-->
  
  <!--전체 편성표 -->
  <!--  <table class="table table-bordered table-hover">-->
  <!--  <thead>-->
  <!--    <tr>-->
  <!--      <th scope="col">시간</th>-->
  <!--      <th scope="col">OCN</th>-->
  <!--      <th scope="col">Channel CGV</th>-->
  <!--      <th scope="col">SUPER ACTION</th>-->
  <!--      <th scope="col">SCREEN</th>-->
  <!--    </tr>-->
  <!--  </thead>-->
  <!--  <tbody>-->
  <!--    {% for date, item in data.items %}-->
  <!--      <tr>-->
  <!--        <th scope="row">{{ date }}</th>-->
  <!--        {% for channel, movies in item.items %}-->
  <!--          <td v-if="selected">-->
  <!--            {% for hour, each_movie in movies.items %}-->
  <!--            <a href="{% url 'watch:go_to' each_movie %}" class="list-group list-group-flush list-group-item-action active">-->
  <!--              <div>{{ hour }} {{ each_movie }}</div>-->
  <!--            </a>-->
  <!--          {% endfor %}-->
  <!--          </td>-->
  <!--        {% endfor %}-->
  <!--      </tr>-->
  <!--    {% endfor %}-->
  <!--  </tbody>-->
  <!--</table>-->
    
    <!--<div class="container">-->
    <!--    {% for date, item in data.items %}-->
    <!--    <p>-->
    <!--      <h4>{{ date }}</h4>-->
    <!--      {% for channel, movies in item.items %}-->
    <!--        <h5>{{ channel }}</h5>-->
    <!--        {% for hour, each_movie in movies.items %}-->
    <!--          <a href="{% url 'watch:go_to' each_movie %}" class="list-group list-group-flush list-group-item-action active">-->
    <!--            <div>{{ hour }} {{ each_movie }}</div>-->
    <!--          </a>-->
    <!--        {% endfor %}-->
    <!--      {% endfor %}-->
    <!--    </p>-->
    <!--    <br>-->
    <!--    {% endfor %}-->
    <!--</div>-->
  </div>
</div>
<script>
  // const app = new Vue({
  //   delimiters: ['[[', ']]'],
  //   el: '#app',
  //   data: {
  //     'selected': '',
  //     // 'submitted': true,
  //     'schedules': {},
  //     'search_schedules': {},
  //     'dates': {},
  //   },
  //   methods: {
  //     search_table: function (channel) {
  //       axios.get(`/search_table/${channel}/`)
  //         .then((response) => {
  //           console.log(response)
  //           return response.data
  //         })
  //         .then((data) => {
  //           this.search_schedules = JSON.parse(data.search_schedules)
  //         })
  //       // this.submitted = true
  //     }
  //   },
  //   beforeMount: function() {
      // this.search_table({{ channel_name  }})
      // this.search_table('ocn')
      // this.schedules = JSON.parse(document.getElementById('app').getAttribute('data') || '{}')
      // for (let schedule in this.schedules) {
      //   console.log(schedule)
      //   let already_judge = false
      //   for (let in_value in this.dates) {
      //     console.log(in_value)
      //     if (in_value == schedule) {
      //       already_judge = true
      //     }
      //   }
      //   if (!already_judge) {
      //     // this.dates[]
      //   }
      // }
      // console.log(this.dates)
      // console.log(this.schedules)
    }
  })
</script>
{% endblock %}

watch/templates/watch/schedule_channel.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}
{% load bootstrap4 %}

{% block head %}
<link href="{% static 'css/search_bar.css'%}" rel='stylesheet'>
<!-- Vue -->
<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
<style>
  .margin-bot {
    margin-bottom: 100px !important;
  }
</style>
{% endblock %}

{% block body %} 
 <nav class="">
  <div class="nav-wrapper row center">
      <div class="row center">
        <form class="form-inline" action="{% url 'watch:search_movie' %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            {% buttons %}
              <button class="btn btn-color btn-xs ml-1" type="submit">검색</button>
            {% endbuttons %}
        </form>
      </div>
  </div>
</nav>
<div>
  <div class="container">
    <!-- select option 채널 -->
    <form class="form-inline" action="{% url 'watch:search_schedule' %}" method="POST">
      {% csrf_token %}
      <label class="my-1 mr-2" for="inlineFormCustomSelectPref">편성표 보기</label>
      <select v-model="selected" class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref" name="channel_name">
        <option selected>채널선택</option>
        <option value="ocn">OCN</option>
        <option value="cgv">채널 CGV</option>
        <option value="super_action">Super Action</option>
        <option value="스크린">Screen</option>
      </select>
      <button class="btn btn-primary my-1">검색</button>
    </form>
    <!-- 편성표 -->
    {% if channel_name == 'cgv' %}
      <h4 class="mx-auto">채널 CGV</h4>
    {% elif channel_name == 'super_action' %}
      <h4>Super Action</h4>
    {% else %}
      <h4 class="mx-auto">{{ channel_name }}</h4>
    {% endif %}
<table class="table table-bordered table-hover margin-bot">
    <thead>
      <tr>
        <th scope="col">시간</th>
        <th scope="col">편성 내역</th>
      </tr>
    </thead>
    <tbody>
      {% for date, item in search_schedules.items %}
        <tr>
          <th scope="row">{{ date }}</th>
          {% for channel, movies in item.items %}
            {% if channel == channel_name %}
              <td>
                {% for hour, each_movie in movies.items %}
                <a href="{% url 'watch:go_to' each_movie %}" class="list-group list-group-flush list-group-item-action active">
                  <div>{{ hour }} {{ each_movie }}</div>
                </a>
              {% endfor %}
              </td>
            {% endif %}
          {% endfor %}
        </tr>
      {% endfor %}
    </tbody>
  </table>
  </div>
</div>
{% endblock %}