accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('follow/<int:movie_id>/', views.follow, name="follow"),
]

movie/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('watch.urls')),
    path('accounts/', include('accounts.urls')),
]

watch/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'watch'

urlpatterns = [
    path('', views.index, name='index'),
    path('schedule/', views.schedule, name='schedule'),
    path('zzims/', views.zzim_list, name='zzim_list'),
    path('mypage/', views.mypage, name='mypage'),
    path('movies/<int:movie_id>/', views.movie_detail, name="movie_detail"),
    path('search_movie/', views.search_movie, name="search_movie"),
    # path('make_schedule/', views.make_schedule, name='make_schedule'),
    path('make_movie/', views.make_movie, name='make_movie'),
    path('go_to/<str:movie_name>/', views.go_to, name="go_to"),
    path('movies/<int:movie_id>/create_comment/', views.create_comment, name="create_comment"),
    url(r'^movie-autocomplete/', views.MovieAutocomplete.as_view(), name='movie-autocomplete'),
    path('schedule/search/', views.search_schedule, name='search_schedule'),
]

templates/base.html
{% load staticfiles %}
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <title>낙낙(Knock Knock)</title>
  {% block head%}
  {% endblock %}
  <!--나눔고딕-->
  <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic|Noto+Sans+KR" rel="stylesheet">
  <!--Noto Sans KR font-->
  <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR" rel="stylesheet">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  <!--Bootstrap css-->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!--jQuery-->
  <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
  <!-- CSS  -->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="{% static 'css/materialize.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen,projection"/>
  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="{% static 'js/materialize.js' %}"></script>
  <script src="{% static 'js/init.js' %}"></script>
  <!-- axios -->
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <style>
   body {
      font-family: 'Nanum Gothic', sans-serif;
   }
   h1,h2,h3,h4,h5,h6 {
      font-family: 'Noto Sans KR', sans-serif;
    }
  </style>
</head>
<body>
  
  
  {% block body %}
  {% endblock %}
  <!--white-->
  <nav class=" navbar-fixed-bottom navbar-mobile btn-group btn-group-justified fixed-bottom" role="group" style="background-color:#26a69a">
    <div class="nav-wrapper container">
      <!-- <a id="logo-container" href="#" class="brand-logo">Logo</a> -->

      <!--  right hide-on-med-and-down -->
      <ul class="d-flex justify-content-around">
        <li ><a href="{% url 'watch:index' %}" class="text-white">홈</a></li>
        <li><a href="{% url 'watch:schedule' %}" class="text-white">편성표</a></li>
        <li><a href="{% url 'watch:zzim_list' %}" class="text-white">찜</a></li>
        <li><a href="{% url 'watch:mypage' %}" class="text-white">마이페이지</a></li>
      </ul>

      <!-- <ul id="nav-mobile" class="sidenav">
        <li><a href="#">Navbar Link</a></li>
      </ul> -->
      <!-- class="sidenav-trigger" -->
      <!-- <a href="#" data-target="nav-mobile" ><i class="material-icons">menu</i></a> -->
    </div>
  </nav>
  
  <!-- Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <!-- jQuery -->
  <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
  {{ form.media }}
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'watch:index' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'watch:schedule' %}">편성표</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'watch:zzim_list' %}">찜</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'watch:mypage' %}">마이페이지</a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:logout' %}">로그아웃</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:signup' %}">회원가입</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">로그인</a>
        </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>